# Generated by Django 3.0.4 on 2020-03-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stepwise', models.BooleanField()),
                ('no_steps', models.IntegerField(blank=True, null=True)),
                ('randyn', models.BooleanField()),
                ('randq', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('number', models.IntegerField(blank=True)),
                ('timepoint', models.CharField(blank=True, max_length=5)),
                ('has_vac', models.BooleanField(blank=True)),
                ('sample', models.CharField(blank=True, max_length=20)),
                ('SampleType', models.ManyToManyField(blank=True, to='main_app.SampleType')),
                ('groupset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.GroupSet')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.VisitType')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('No_subjects', models.IntegerField()),
                ('groupset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.GroupSet')),
            ],
        ),
    ]
